const defaultObj = {
    name: "Creamy Veggie Tuna Pasta Salad",
    instructions: [
      {
        position: 1,
        display_text:
          "In a large bowl, combine the lemon zest, lemon juice, and red onion. Let pickle for about 15 minutes.",
        start_time: 9166,
        appliance: null,
        end_time: 17433,
        temperature: null,
        id: 71398,
      },
      {
        temperature: null,
        id: 71399,
        position: 2,
        display_text:
          "Remove the stems from the yellow and red bell peppers. Cut off the sides of the peppers, keeping the seeds and tops intact in the centers, then slice into strips and dice into small pieces. Transfer the bell peppers to the bowl with the pickled onion, along with the diced celery, grated carrots, tuna, and pasta. Toss to combine.",
        start_time: 18000,
        appliance: null,
        end_time: 58000,
      },
      {
        appliance: null,
        end_time: 80933,
        temperature: null,
        id: 71400,
        position: 3,
        display_text:
          "Make the herb mayo dressing: In a small bowl, combine the cumin seeds, turmeric, white vinegar, Dijon mustard, Hellmann’s® Mayonnaise, salt, red pepper flakes, black pepper, basil, chives, and carrot tops. Whisk until smooth.",
        start_time: 59000,
      },
      {
        appliance: null,
        end_time: 90700,
        temperature: null,
        id: 71401,
        position: 4,
        display_text:
          "Pour the dressing over the pasta salad and toss until well coated.",
        start_time: 82766,
      },
      {
        id: 71402,
        position: 5,
        display_text: "Garnish with the celery leaves and serve immediately.",
        start_time: 92000,
        appliance: null,
        end_time: 96333,
        temperature: null,
      },
      {
        id: 71403,
        position: 6,
        display_text: "Enjoy!",
        start_time: 98000,
        appliance: null,
        end_time: 99166,
        temperature: null,
      },
    ],
    yields: "Servings: 4–6",
    originalVideo:
      "https://s3.amazonaws.com/video-api-prod/assets/4afcf5d9e071423fbece86f1cfd26184/Hellmanns_ZeroWaste_BFV90115_FB.mp4",
    prepTime: null,
    totalTime: { tier: "under_30_minutes", display_tier: "Under 60 minutes" },
    thumbnail:
      "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/374817.jpg",
    supplies: [
      {
        components: [
          {
            ingredient: {
              display_plural: "lemons",
              id: 155,
              display_singular: "lemon",
              updated_at: 1509035282,
              name: "lemon",
              created_at: 1493906426,
            },
            id: 93804,
            position: 1,
            measurements: [
              {
                unit: {
                  system: "none",
                  name: "",
                  display_plural: "",
                  display_singular: "",
                  abbreviation: "",
                },
                quantity: "1",
                id: 688680,
              },
            ],
            raw_text: "Zest of 1 lemon",
            extra_comment: "zested",
          },
          {
            raw_text: "Juice of 1 lemon",
            extra_comment: "juiced",
            ingredient: {
              display_plural: "lemons",
              id: 155,
              display_singular: "lemon",
              updated_at: 1509035282,
              name: "lemon",
              created_at: 1493906426,
            },
            id: 93805,
            position: 2,
            measurements: [
              {
                quantity: "1",
                id: 688683,
                unit: {
                  system: "none",
                  name: "",
                  display_plural: "",
                  display_singular: "",
                  abbreviation: "",
                },
              },
            ],
          },
          {
            raw_text: "½ small red onion, diced",
            extra_comment: "diced",
            ingredient: {
              created_at: 1495149178,
              display_plural: "small red onions",
              id: 492,
              display_singular: "small red onion",
              updated_at: 1509035256,
              name: "small red onion",
            },
            id: 93806,
            position: 3,
            measurements: [
              {
                unit: {
                  system: "none",
                  name: "",
                  display_plural: "",
                  display_singular: "",
                  abbreviation: "",
                },
                quantity: "½",
                id: 688682,
              },
            ],
          },
          {
            id: 93807,
            position: 4,
            measurements: [
              {
                unit: {
                  display_singular: "",
                  abbreviation: "",
                  system: "none",
                  name: "",
                  display_plural: "",
                },
                quantity: "1",
                id: 688695,
              },
            ],
            raw_text: "1 small yellow bell pepper",
            extra_comment: "",
            ingredient: {
              created_at: 1503765611,
              display_plural: "small yellow bell peppers",
              id: 2898,
              display_singular: "small yellow bell pepper",
              updated_at: 1509035101,
              name: "small yellow bell pepper",
            },
          },
          {
            measurements: [
              {
                unit: {
                  display_singular: "",
                  abbreviation: "",
                  system: "none",
                  name: "",
                  display_plural: "",
                },
                quantity: "1",
                id: 688681,
              },
            ],
            raw_text: "1 small red bell pepper",
            extra_comment: "",
            ingredient: {
              updated_at: 1509035101,
              name: "small red bell pepper",
              created_at: 1503765661,
              display_plural: "small red bell peppers",
              id: 2899,
              display_singular: "small red bell pepper",
            },
            id: 93808,
            position: 5,
          },
          {
            raw_text: "3–4 celery stalks, diced",
            extra_comment: "diced",
            ingredient: {
              display_singular: "celery stalk",
              updated_at: 1528398587,
              name: "celery stalk",
              created_at: 1528398587,
              display_plural: "celery stalks",
              id: 4296,
            },
            id: 93809,
            position: 6,
            measurements: [
              {
                unit: {
                  abbreviation: "",
                  system: "none",
                  name: "",
                  display_plural: "",
                  display_singular: "",
                },
                quantity: "3",
                id: 688684,
              },
            ],
          },
          {
            extra_comment: "grated, tops reserved for dressing",
            ingredient: {
              id: 27,
              display_singular: "carrot",
              updated_at: 1509035288,
              name: "carrot",
              created_at: 1493314877,
              display_plural: "carrots",
            },
            id: 93810,
            position: 7,
            measurements: [
              {
                unit: {
                  system: "none",
                  name: "",
                  display_plural: "",
                  display_singular: "",
                  abbreviation: "",
                },
                quantity: "2",
                id: 688689,
              },
            ],
            raw_text: "2 carrots, grated, tops reserved for dressing",
          },
          {
            raw_text: "12 ounces solid white canned tuna in water, drained",
            extra_comment: "drained",
            ingredient: {
              created_at: 1650915628,
              display_plural: "solid white canned tuna in water",
              id: 9700,
              display_singular: "solid white canned tuna in water",
              updated_at: 1650915628,
              name: "solid white canned tuna in water",
            },
            id: 93811,
            position: 8,
            measurements: [
              {
                quantity: "355",
                id: 688688,
                unit: {
                  display_plural: "g",
                  display_singular: "g",
                  abbreviation: "g",
                  system: "metric",
                  name: "gram",
                },
              },
              {
                quantity: "12",
                id: 688686,
                unit: {
                  display_plural: "oz",
                  display_singular: "oz",
                  abbreviation: "oz",
                  system: "imperial",
                  name: "ounce",
                },
              },
            ],
          },
          {
            measurements: [
              {
                unit: {
                  system: "metric",
                  name: "gram",
                  display_plural: "g",
                  display_singular: "g",
                  abbreviation: "g",
                },
                quantity: "225",
                id: 688687,
              },
              {
                unit: {
                  display_singular: "oz",
                  abbreviation: "oz",
                  system: "imperial",
                  name: "ounce",
                  display_plural: "oz",
                },
                quantity: "8",
                id: 688685,
              },
            ],
            raw_text:
              "8 ounces dried farfalle pasta, cooked according to package instructions",
            extra_comment: "cooked acording to package instructions",
            ingredient: {
              name: "dried farfalle pasta",
              created_at: 1650915659,
              display_plural: "dried farfalle pastas",
              id: 9701,
              display_singular: "dried farfalle pasta",
              updated_at: 1650915659,
            },
            id: 93812,
            position: 9,
          },
          {
            raw_text: "¼ cup celery leaves, finely chopped",
            extra_comment: "finely chopped",
            ingredient: {
              name: "celery",
              created_at: 1495082620,
              display_plural: "celeries",
              id: 458,
              display_singular: "celery",
              updated_at: 1509035259,
            },
            id: 93813,
            position: 10,
            measurements: [
              {
                unit: {
                  display_plural: "g",
                  display_singular: "g",
                  abbreviation: "g",
                  system: "metric",
                  name: "gram",
                },
                quantity: "10",
                id: 688694,
              },
              {
                unit: {
                  abbreviation: "c",
                  system: "imperial",
                  name: "cup",
                  display_plural: "cups",
                  display_singular: "cup",
                },
                quantity: "¼",
                id: 688693,
              },
            ],
          },
        ],
        name: null,
        position: 1,
      },
      {
        components: [
          {
            ingredient: {
              display_singular: "whole cumin seed",
              updated_at: 1526410222,
              name: "whole cumin seeds",
              created_at: 1526410222,
              display_plural: "whole cumin seeds",
              id: 4096,
            },
            id: 93815,
            position: 12,
            measurements: [
              {
                id: 688690,
                unit: {
                  system: "imperial",
                  name: "teaspoon",
                  display_plural: "teaspoons",
                  display_singular: "teaspoon",
                  abbreviation: "tsp",
                },
                quantity: "½",
              },
            ],
            raw_text: "½ teaspoon whole cumin seeds, lightly toasted",
            extra_comment: "lightly toasted",
          },
          {
            measurements: [
              {
                unit: {
                  display_singular: "teaspoon",
                  abbreviation: "tsp",
                  system: "imperial",
                  name: "teaspoon",
                  display_plural: "teaspoons",
                },
                quantity: "¼",
                id: 688705,
              },
            ],
            raw_text: "¼ teaspoon ground turmeric",
            extra_comment: "",
            ingredient: {
              display_plural: "ground turmerics",
              id: 1293,
              display_singular: "ground turmeric",
              updated_at: 1509035196,
              name: "ground turmeric",
              created_at: 1496674140,
            },
            id: 93816,
            position: 13,
          },
          {
            position: 14,
            measurements: [
              {
                id: 688703,
                unit: {
                  display_singular: "tablespoon",
                  abbreviation: "tbsp",
                  system: "imperial",
                  name: "tablespoon",
                  display_plural: "tablespoons",
                },
                quantity: "2 ½",
              },
            ],
            raw_text: "2½ tablespoons white vinegar",
            extra_comment: "",
            ingredient: {
              updated_at: 1509035264,
              name: "white vinegar",
              created_at: 1494981978,
              display_plural: "white vinegars",
              id: 392,
              display_singular: "white vinegar",
            },
            id: 93817,
          },
          {
            raw_text: "1 tablespoon Dijon mustard",
            extra_comment: "",
            ingredient: {
              updated_at: 1509035271,
              name: "dijon mustard",
              created_at: 1494812213,
              display_plural: "dijon mustards",
              id: 307,
              display_singular: "dijon mustard",
            },
            id: 93818,
            position: 15,
            measurements: [
              {
                unit: {
                  system: "imperial",
                  name: "tablespoon",
                  display_plural: "tablespoons",
                  display_singular: "tablespoon",
                  abbreviation: "tbsp",
                },
                quantity: "1",
                id: 688691,
              },
            ],
          },
          {
            measurements: [
              {
                quantity: "80",
                id: 688697,
                unit: {
                  display_plural: "g",
                  display_singular: "g",
                  abbreviation: "g",
                  system: "metric",
                  name: "gram",
                },
              },
              {
                unit: {
                  system: "imperial",
                  name: "cup",
                  display_plural: "cups",
                  display_singular: "cup",
                  abbreviation: "c",
                },
                quantity: "⅓",
                id: 688696,
              },
            ],
            raw_text: "⅓ cup Hellmann's® Mayonnaise",
            extra_comment: "",
            ingredient: {
              display_plural: "Hellmann's® Mayonnaises",
              id: 9702,
              display_singular: "Hellmann's® Mayonnaise",
              updated_at: 1650915759,
              name: "Hellmann's® Mayonnaise",
              created_at: 1650915759,
            },
            id: 93819,
            position: 16,
          },
          {
            id: 93820,
            position: 17,
            measurements: [
              {
                unit: {
                  system: "imperial",
                  name: "teaspoon",
                  display_plural: "teaspoons",
                  display_singular: "teaspoon",
                  abbreviation: "tsp",
                },
                quantity: "1",
                id: 688692,
              },
            ],
            raw_text: "1 teaspoon kosher salt",
            extra_comment: "",
            ingredient: {
              updated_at: 1509035289,
              name: "kosher salt",
              created_at: 1493307153,
              display_plural: "kosher salts",
              id: 11,
              display_singular: "kosher salt",
            },
          },
          {
            id: 93821,
            position: 18,
            measurements: [
              {
                quantity: "¼",
                id: 688699,
                unit: {
                  display_singular: "teaspoon",
                  abbreviation: "tsp",
                  system: "imperial",
                  name: "teaspoon",
                  display_plural: "teaspoons",
                },
              },
            ],
            raw_text: "¼ teaspoon red pepper flakes",
            extra_comment: "",
            ingredient: {
              name: "red pepper flakes",
              created_at: 1494885083,
              display_plural: "red pepper flakes",
              id: 351,
              display_singular: "red pepper flake",
              updated_at: 1509035267,
            },
          },
          {
            position: 19,
            measurements: [
              {
                unit: {
                  display_plural: "teaspoons",
                  display_singular: "teaspoon",
                  abbreviation: "tsp",
                  system: "imperial",
                  name: "teaspoon",
                },
                quantity: "½",
                id: 688704,
              },
            ],
            raw_text: "½ teaspoon freshly ground black pepper",
            extra_comment: "",
            ingredient: {
              name: "freshly ground black pepper",
              created_at: 1493925438,
              display_plural: "freshly ground black peppers",
              id: 166,
              display_singular: "freshly ground black pepper",
              updated_at: 1509035282,
            },
            id: 93822,
          },
          {
            ingredient: {
              display_plural: "large fresh basil leaves",
              id: 6426,
              display_singular: "large fresh basil leaf",
              updated_at: 1589818945,
              name: "large fresh basil leaves",
              created_at: 1589818945,
            },
            id: 93823,
            position: 20,
            measurements: [
              {
                unit: {
                  system: "none",
                  name: "",
                  display_plural: "",
                  display_singular: "",
                  abbreviation: "",
                },
                quantity: "4",
                id: 688698,
              },
            ],
            raw_text: "4 large fresh basil leaves and stems, finely chopped",
            extra_comment: "finely chopped",
          },
          {
            measurements: [
              {
                unit: {
                  display_plural: "g",
                  display_singular: "g",
                  abbreviation: "g",
                  system: "metric",
                  name: "gram",
                },
                quantity: "10",
                id: 688702,
              },
              {
                unit: {
                  system: "imperial",
                  name: "cup",
                  display_plural: "cups",
                  display_singular: "cup",
                  abbreviation: "c",
                },
                quantity: "¼",
                id: 688700,
              },
            ],
            raw_text: "¼ cup finely chopped fresh chives",
            extra_comment: "finely chopped",
            ingredient: {
              updated_at: 1509035154,
              name: "fresh chives",
              created_at: 1498567386,
              display_plural: "fresh chives",
              id: 1947,
              display_singular: "fresh chive",
            },
            id: 93824,
            position: 21,
          },
          {
            measurements: [
              {
                unit: {
                  system: "none",
                  name: "",
                  display_plural: "",
                  display_singular: "",
                  abbreviation: "",
                },
                quantity: "0",
                id: 688701,
              },
            ],
            raw_text: "Reserved carrot tops and stems, finely chopped",
            extra_comment: "finely chopped",
            ingredient: {
              created_at: 1650915904,
              display_plural: "reserved carrot tops and stems",
              id: 9703,
              display_singular: "reserved carrot tops and stem",
              updated_at: 1650915904,
              name: "reserved carrot tops and stems",
            },
            id: 93825,
            position: 22,
          },
        ],
        name: "Herb Mayo Dressing",
        position: 2,
      },
    ],
  }

export default defaultObj